### ISSUE TITLE
Presolver class docs should note that variables are relabeled

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-preprocessing#59]
Currently a user would not expect that the model in the Presolver class is relabled to integer labels:

```
>>> cqm.variables
Variables(['a'])
>>> pre = Presolver(cqm)
>>> cqm2 = pre.copy_model()
>>> cqm2.variables
Variables([0])
```

Question: Is this to reduce the in-memory CQM size similar to when big CQMs are uploaded by `LeapHybridCQMSampler()` for example? It would be easier to use the copies if they kept the variable names of the original.

**Comment by arcondello** [comment]
Agree we should note it.

While the models are mathematically equivalent, the variables themselves do not have a direct relationship. Presolve will remove variables, add variables, scale biases, change the vartype of variables, substitute variables, etc. So we very quickly get into ship of Theseus territory and leaving the original labels on would be misleading.
